name: ReportUI
author: Taylcd
website: https://github.com/Taylcd/ReportUI

version: 1.3.1
api:
  - 3.0.0-ALPHA7
  - 3.0.0-ALPHA8
  - 3.0.0-ALPHA9
  - 3.0.0-ALPHA10
  - 3.0.0-ALPHA11
  - 3.0.0-ALPHA12

main: Taylcd\ReportUI\ReportUI

commands:
  report:
    description: Пожаловаться на игрока
    permission: report.use
  reportadmin:
    description: Открыть Админ панель
    permission: report.admin

permissions:
  report.use:
    default: true
  report.admin:
    default: op
  report.admin.notification:
    default: op
